"""Compatibility matrix: deterministic render of committed state to markdown.

The committed ``docs/compatibility-matrix.md`` is generated, never hand
edited; :func:`check_matrix` is the staleness gate CI runs. The render reads
COMMITTED state only (CON-12): every input — the standards manifest (rows,
the mirrored ``sdk_compatibility`` block, the dependency-policy block), the
corpus manifest (retained versions), the promotion records, ``pyproject.toml``
and ``.gitmodules`` — is read from the commit HEAD records wherever HEAD
verifies (a path HEAD does not carry is committed-absent: required inputs
refuse, the optional promotion-records input skips). The working tree is
read only where no committed copy can exist to diverge from — a non-git
root, or a repository whose HEAD is merely unborn — and a repository that
exists but cannot be read refuses loudly rather than substituting
working-tree bytes (``_committed_bytes`` states the exact breadth). The
git invocations run with GIT_* environment variables scrubbed, so a
caller's environment cannot redirect the committed read. No remote URL and
no submodule init enters it, so a fork clone, a moved submodule or an
uncommitted local edit cannot change a rendered byte.
Commit SHAs are deliberately absent — they move per checkout — and stay in
the ``versions`` output instead.

Two tables: one row per canonical standard (identity, status, SDK pairing,
migration guidance) and one row per RETAINED version — stage, range
membership, yank/deprecation, and the from-predecessor migration note
(VR-52's release-review walk, rendered from the policy block and the
promotion records).
"""

from __future__ import annotations

import os
import subprocess
import tempfile
import tomllib
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from .manifest import (
    StandardEntry,
    StandardsError,
    load_dependency_policy,
    load_manifest,
    load_sdk_compatibility,
    retained_versions,
    served_versions,
    version_tuple,
)
from .promotion import load_promotion_records

DOCS_PATH = "docs/compatibility-matrix.md"
GENERATED_MARKER = "<!-- Generated by benchweave.standards matrix — do not edit manually. -->"
HEADER = (
    "| Standard | Schema/protocol version | Status | SDK version "
    "| Main-project range | Migration guidance | Sources |"
)
RULE = "| --- | --- | --- | --- | --- | --- | --- |"
#: The per-version table's header (VR-52): one row per retained version.
VERSION_HEADER = (
    "| Standard | Version | Stage | Range | Yank / deprecation | Migration note |"
)
VERSION_RULE = "| --- | --- | --- | --- | --- | --- |"

#: Committed inputs the render reads (CON-12's purity clause, extended to
#: the per-version rows' new inputs — the policy block and the promotion
#: records). promotion-records.json is optional by its loader's own
#: contract (absent = no recorded promotions); the other four are required.
_COMMITTED_INPUTS = (
    "standards/standards-manifest.json",
    "standards/corpus-manifest.json",
    "standards/promotion-records.json",
    "pyproject.toml",
    ".gitmodules",
)
_REQUIRED_INPUTS = frozenset(_COMMITTED_INPUTS) - {"standards/promotion-records.json"}


def _git_result(root: Path, *arguments: str) -> subprocess.CompletedProcess[bytes] | None:
    """One git invocation, immune to GIT_* environment redirection.

    The committed read's authority is the root's own repository: a caller's
    or a harness's ``GIT_DIR``/``GIT_WORK_TREE``/... must not be able to
    point it elsewhere, so every GIT_* variable is scrubbed from the
    child's environment (the same reason check.py reads the submodule
    through its own object store). ``None`` only when git cannot even
    start — the callers treat that as an unreadable repository, never as
    "no committed copy".
    """
    environment = {
        key: value for key, value in os.environ.items() if not key.startswith("GIT_")
    }
    try:
        return subprocess.run(  # noqa: S603 — fixed argv
            ["git", "-C", str(root), *arguments],  # noqa: S607 — PATH git is the supported invocation
            capture_output=True,
            check=False,
            env=environment,
        )
    except OSError:
        return None


def _committed_bytes(root: Path, relative: str) -> bytes | None:
    """HEAD's bytes for ``relative``; None when HEAD carries no copy.

    The fallback's breadth is exact (fold FIX B, #219 refute wave):

    - a root whose HEAD verifies is STRICT — the path is read from HEAD or
      is committed-absent (``None``); the working tree is never consulted,
      so an uncommitted edit or an untracked file cannot move a rendered
      byte;
    - the working tree is read ONLY where no committed copy can exist to
      diverge from: the root is not a git repository at all, or the
      repository exists and HEAD is merely unborn (the non-git and
      ``git init``-no-commit test fixtures — CON-12's dual posture);
    - a repository that exists but cannot be read (corrupt HEAD, ambiguous
      refs, a git failure that is neither "no repo" nor "unborn") refuses
      loudly (``StandardsError``) — rendering working-tree bytes from a
      repo whose history is unreadable would launder uncommitted state as
      committed.
    """
    head = _git_result(root, "rev-parse", "--verify", "--quiet", "HEAD")
    if head is not None and head.returncode == 0:
        shown = _git_result(root, "show", f"HEAD:./{relative}")
        if shown is not None and shown.returncode == 0:
            return shown.stdout
        return None  # committed-absent: the path is not in HEAD
    # No verified HEAD. Distinguish "no history can exist here" from
    # "history exists but cannot be read" — only the former may fall back.
    gitdir = _git_result(root, "rev-parse", "--absolute-git-dir")
    if gitdir is None or gitdir.returncode != 0:
        if not (root / ".git").exists():
            # Not a git checkout at all: the working tree is the only
            # input there is. A file absent here too is committed-absent
            # (the caller refuses for required inputs, skips for optional).
            try:
                return (root / relative).read_bytes()
            except FileNotFoundError:
                return None
        raise StandardsError(
            "matrix_committed_state_unreadable: the root carries a .git but "
            "its history cannot be read (git rev-parse failed); the matrix "
            "renders committed state only and will not substitute "
            "working-tree bytes"
        )
    symbolic = _git_result(root, "symbolic-ref", "-q", "HEAD")
    if symbolic is not None and symbolic.returncode == 0:
        # Unborn HEAD: a repository with no commits — nothing has ever been
        # committed here, so there is no committed copy to diverge from.
        try:
            return (root / relative).read_bytes()
        except FileNotFoundError:
            return None
    raise StandardsError(
        "matrix_committed_state_unreadable: HEAD does not verify and is not "
        "an unborn branch — the repository's history is unreadable; the "
        "matrix renders committed state only and will not substitute "
        "working-tree bytes"
    )


@contextmanager
def _committed_view(root: Path) -> Iterator[Path]:
    """Stage the render's committed inputs in a temp root, then yield it.

    The loaders (manifest, policy, promotion records, the two repo-identity
    reads) keep their exact semantics — they are pointed at a root whose
    files are HEAD's bytes, so no loader learns about git and no
    working-tree state can enter the render. A required input that is
    committed-absent (or absent from a non-git root) refuses
    ``FileNotFoundError`` — the styled CLI path — never a degraded cell;
    the optional promotion-records input skips staging (its loader's own
    absent-means-empty contract).
    """
    with tempfile.TemporaryDirectory(prefix="benchweave-matrix-view-") as tmp:
        view = Path(tmp)
        for relative in _COMMITTED_INPUTS:
            raw = _committed_bytes(root, relative)
            if raw is None:
                if relative in _REQUIRED_INPUTS:
                    raise FileNotFoundError(
                        f"no committed copy of {relative}, a required render "
                        "input; the matrix renders committed state only"
                    )
                continue
            target = view / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
        yield view


def render_matrix(root: Path) -> str:
    """Render the committed-artifact markdown from committed state only.

    Every input is read through :func:`_committed_view` (CON-12): HEAD's
    bytes where HEAD carries them. A missing committed source refuses
    (``StandardsError`` / ``FileNotFoundError``) rather than degrading the
    cell to "unknown" or an unlinked name.
    """
    with _committed_view(root) as view:
        return _render(view)


def _render(view: Path) -> str:
    manifest = load_manifest(view)
    compatibility = load_sdk_compatibility(view)
    policy = load_dependency_policy(view)
    sdk_version = compatibility.sdk
    main_range = compatibility.main_project
    notes = compatibility.notes
    sources = _sources(_main_repo_url(view), _sdk_repo_url(view))
    promoted = {
        (record.standard, record.target): record.dev_head
        for record in load_promotion_records(view)
    }
    lines = [
        GENERATED_MARKER,
        "",
        "# Standards compatibility matrix",
        "",
        "Generated from `standards/standards-manifest.json` and the SDK",
        "`standards-lock.json`. The first table is one row per canonical",
        "standard; the standard version IS the schema/protocol version.",
        "The second table (Retained versions) is the release-review walk of",
        "VR-52: one row per retained version with stage, range membership,",
        "yank/deprecation and the from-predecessor migration note, from the",
        "dependency-policy block and the promotion records. Both render",
        "committed state only. Regenerate with",
        "`uv run python -m benchweave.standards matrix`; CI fails when the",
        "committed file is stale. Commit SHAs are not pinned here — run",
        "`uv run python -m benchweave.standards versions` for them.",
        "",
        HEADER,
        RULE,
    ]
    for entry in manifest.standards:
        lines.append(
            f"| {_cell(entry.id)} | {_cell(entry.version)} | {_cell(entry.status)} "
            f"| {_cell(sdk_version)} | {_cell(main_range)} "
            f"| {_cell(_guidance(entry, notes))} | {sources} |"
        )
    lines += [
        "",
        "## Retained versions",
        "",
        "One row per retained version (the corpus manifest's version",
        "directories), rendered from committed state only: range membership,",
        "yank and the migration note come from the dependency-policy block;",
        "the stage cell names a recorded promotion where one exists.",
        "Pre-adoption releases carry no migration note (SM-5 is from",
        "adoption, design record D6).",
        "",
        VERSION_HEADER,
        VERSION_RULE,
    ]
    for entry in manifest.standards:
        retained = retained_versions(view, entry.id)
        if not retained:
            raise StandardsError(
                f"retained_versions_absent: {entry.id} — the per-version matrix "
                "rows enumerate the corpus manifest, which names no retained "
                "version for this standard"
            )
        row = policy.standards.get(entry.id)
        if row is None:
            # Fail closed: the render derives range/yank/note cells from the
            # policy row; a manifest standard without one has broken
            # governance data (validate_dependency_policy refuses the same
            # state at export).
            raise StandardsError(
                f"dependency_policy_invalid: no policy row for standard {entry.id!r}"
            )
        yanked = {record.version: record for record in row.yanked}
        served = served_versions(policy, view, entry.id)
        move_to = max(served, key=version_tuple) if served else row.lower
        for version in sorted(retained, key=version_tuple):
            stage = promoted.get((entry.id, version))
            stage_cell = f"released (promoted from {stage})" if stage else "released"
            range_cell = "in range" if row.in_range(version) else "out of range"
            record = yanked.get(version)
            if record is None:
                yank_cell = "—"
            else:
                yank_cell = (
                    f"yanked (since {record.since}) — {record.reason}; move-to {move_to}"
                )
            note_cell = row.versions.get(version, "—")
            lines.append(
                f"| {_cell(entry.id)} | {_cell(version)} | {_cell(stage_cell)} "
                f"| {_cell(range_cell)} | {_cell(yank_cell)} | {_cell(note_cell)} |"
            )
    lines.append("")
    return "\n".join(lines)


def check_matrix(root: Path) -> list[str]:
    """``[]`` when the committed matrix equals a fresh render; else one failure."""
    committed = root / DOCS_PATH
    if not committed.is_file():
        return [f"stale_matrix: {DOCS_PATH} absent; run python -m benchweave.standards matrix"]
    if committed.read_text(encoding="utf-8") != render_matrix(root):
        return [
            f"stale_matrix: {DOCS_PATH} differs from the rendered matrix; "
            "run python -m benchweave.standards matrix"
        ]
    return []


def _guidance(entry: StandardEntry, notes: str | None) -> str:
    if entry.status == "deprecated":
        if notes:
            return f"Deprecated — {notes}"
        return "Deprecated — migration guidance pending (compatibility.notes unfilled)"
    if entry.supersedes:
        return f"Supersedes {entry.supersedes}"
    return "—"


def _sources(main_url: str, sdk_url: str) -> str:
    # Both URL helpers fail closed, so the unlinked-cell degradation is
    # unreachable: an honest cell or a refusal, never a silent substitution.
    return f"[main repo]({main_url}) · [sdk repo]({sdk_url})"


def _main_repo_url(root: Path) -> str:
    """Main-repo URL from pyproject ``[project.urls]`` — committed data."""
    with (root / "pyproject.toml").open("rb") as handle:
        urls = tomllib.load(handle).get("project", {}).get("urls", {})
    url = urls.get("Repository") if isinstance(urls, dict) else None
    if not isinstance(url, str) or not url:
        raise StandardsError(
            "main_repo_url_absent: pyproject.toml [project.urls] Repository; "
            "the matrix renders committed files only"
        )
    return url


def _sdk_repo_url(root: Path) -> str:
    """SDK-repo URL from the committed ``.gitmodules`` submodule declaration.

    Routed through :func:`_git_result` for the same GIT_*-scrubbing reason
    as the committed read — the Sources cell must not be redirectable from
    the caller's environment.
    """
    result = _git_result(
        root, "config", "--file", str(root / ".gitmodules"), "--get",
        "submodule.packages/sdk.url",
    )
    url = (
        result.stdout.decode("utf-8", errors="replace").strip()
        if result is not None and result.returncode == 0
        else ""
    )
    if not url:
        raise StandardsError(
            "sdk_repo_url_absent: .gitmodules submodule.packages/sdk.url; "
            "the matrix renders committed files only"
        )
    return url.removesuffix(".git")


def _cell(value: str) -> str:
    # Operator-authored text (compatibility notes, yank reasons, note
    # pointers) must never break the row: neutralise pipes AND newlines,
    # the two characters a markdown table cannot carry.
    return value.replace("|", "\\|").replace("\n", " ")
