"""Compatibility matrix: deterministic render of committed state to markdown.

The committed ``docs/compatibility-matrix.md`` is generated, never hand
edited; :func:`check_matrix` is the staleness gate CI runs. The render reads
COMMITTED state only (CON-12): every input — the standards manifest (rows,
the mirrored ``sdk_compatibility`` block, the dependency-policy block), the
corpus manifest (retained versions), the promotion records, ``pyproject.toml``
and ``.gitmodules`` — is read from the commit HEAD records, falling back to
the working tree only when the root carries no committed copy to diverge
from (the ``check.py`` pyproject@pin dual posture: no pin, no divergence).
No remote URL and no submodule init enters it, so a fork clone, a moved
submodule or an uncommitted local edit cannot change a rendered byte.
Commit SHAs are deliberately absent — they move per checkout — and stay in
the ``versions`` output instead.

Two tables: one row per canonical standard (identity, status, SDK pairing,
migration guidance) and one row per RETAINED version — stage, range
membership, yank/deprecation, and the from-predecessor migration note
(VR-52's release-review walk, rendered from the policy block and the
promotion records).
"""

from __future__ import annotations

import subprocess
import tempfile
import tomllib
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from .manifest import (
    StandardEntry,
    StandardsError,
    load_dependency_policy,
    load_manifest,
    load_sdk_compatibility,
    retained_versions,
    served_versions,
    version_tuple,
)
from .promotion import load_promotion_records

DOCS_PATH = "docs/compatibility-matrix.md"
GENERATED_MARKER = "<!-- Generated by benchweave.standards matrix — do not edit manually. -->"
HEADER = (
    "| Standard | Schema/protocol version | Status | SDK version "
    "| Main-project range | Migration guidance | Sources |"
)
RULE = "| --- | --- | --- | --- | --- | --- | --- |"
#: The per-version table's header (VR-52): one row per retained version.
VERSION_HEADER = (
    "| Standard | Version | Stage | Range | Yank / deprecation | Migration note |"
)
VERSION_RULE = "| --- | --- | --- | --- | --- | --- |"

#: Committed inputs the render reads (CON-12's purity clause, extended to
#: the per-version rows' new inputs — the policy block and the promotion
#: records). promotion-records.json is optional by its loader's own
#: contract (absent = no recorded promotions); the other four are required.
_COMMITTED_INPUTS = (
    "standards/standards-manifest.json",
    "standards/corpus-manifest.json",
    "standards/promotion-records.json",
    "pyproject.toml",
    ".gitmodules",
)
_REQUIRED_INPUTS = frozenset(_COMMITTED_INPUTS) - {"standards/promotion-records.json"}


def _committed_bytes(root: Path, relative: str) -> bytes:
    """HEAD's bytes for ``relative``; the working tree when HEAD has none.

    ``git show`` fails when the root is not a git checkout, HEAD is
    unborn, or the file was never committed — in each case there is no
    committed copy to diverge from, so the working tree is the only input
    (the ``_pinned_sdk_package_version`` dual posture, CON-12's
    2026-09-25 amendment). A git invocation that cannot even start
    degrades to the same fallback; the file read that follows refuses by
    name when nothing exists.
    """
    try:
        result = subprocess.run(  # noqa: S603 — fixed argv
            ["git", "-C", str(root), "show", f"HEAD:./{relative}"],  # noqa: S607 — PATH git is the supported invocation
            capture_output=True,
            check=False,
        )
    except OSError:
        result = None
    if result is not None and result.returncode == 0:
        return result.stdout
    return (root / relative).read_bytes()


@contextmanager
def _committed_view(root: Path) -> Iterator[Path]:
    """Stage the render's committed inputs in a temp root, then yield it.

    The loaders (manifest, policy, promotion records, the two repo-identity
    reads) keep their exact semantics — they are pointed at a root whose
    files are HEAD's bytes, so no loader learns about git and no
    working-tree state can enter the render.
    """
    with tempfile.TemporaryDirectory(prefix="benchweave-matrix-view-") as tmp:
        view = Path(tmp)
        for relative in _COMMITTED_INPUTS:
            try:
                raw = _committed_bytes(root, relative)
            except FileNotFoundError:
                if relative in _REQUIRED_INPUTS:
                    raise
                continue
            target = view / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
        yield view


def render_matrix(root: Path) -> str:
    """Render the committed-artifact markdown from committed state only.

    Every input is read through :func:`_committed_view` (CON-12): HEAD's
    bytes where HEAD carries them. A missing committed source refuses
    (``StandardsError`` / ``FileNotFoundError``) rather than degrading the
    cell to "unknown" or an unlinked name.
    """
    with _committed_view(root) as view:
        return _render(view)


def _render(view: Path) -> str:
    manifest = load_manifest(view)
    compatibility = load_sdk_compatibility(view)
    policy = load_dependency_policy(view)
    sdk_version = compatibility.sdk
    main_range = compatibility.main_project
    notes = compatibility.notes
    sources = _sources(_main_repo_url(view), _sdk_repo_url(view))
    promoted = {
        (record.standard, record.target): record.dev_head
        for record in load_promotion_records(view)
    }
    lines = [
        GENERATED_MARKER,
        "",
        "# Standards compatibility matrix",
        "",
        "Generated from `standards/standards-manifest.json` and the SDK",
        "`standards-lock.json`. The first table is one row per canonical",
        "standard; the standard version IS the schema/protocol version.",
        "The second table (Retained versions) is the release-review walk of",
        "VR-52: one row per retained version with stage, range membership,",
        "yank/deprecation and the from-predecessor migration note, from the",
        "dependency-policy block and the promotion records. Both render",
        "committed state only. Regenerate with",
        "`uv run python -m benchweave.standards matrix`; CI fails when the",
        "committed file is stale. Commit SHAs are not pinned here — run",
        "`uv run python -m benchweave.standards versions` for them.",
        "",
        HEADER,
        RULE,
    ]
    for entry in manifest.standards:
        lines.append(
            f"| {_cell(entry.id)} | {_cell(entry.version)} | {_cell(entry.status)} "
            f"| {_cell(sdk_version)} | {_cell(main_range)} "
            f"| {_cell(_guidance(entry, notes))} | {sources} |"
        )
    lines += [
        "",
        "## Retained versions",
        "",
        "One row per retained version (the corpus manifest's version",
        "directories), rendered from committed state only: range membership,",
        "yank and the migration note come from the dependency-policy block;",
        "the stage cell names a recorded promotion where one exists.",
        "Pre-adoption releases carry no migration note (SM-5 is from",
        "adoption, design record D6).",
        "",
        VERSION_HEADER,
        VERSION_RULE,
    ]
    for entry in manifest.standards:
        retained = retained_versions(view, entry.id)
        if not retained:
            raise StandardsError(
                f"retained_versions_absent: {entry.id} — the per-version matrix "
                "rows enumerate the corpus manifest, which names no retained "
                "version for this standard"
            )
        row = policy.standards.get(entry.id)
        if row is None:
            # Fail closed: the render derives range/yank/note cells from the
            # policy row; a manifest standard without one has broken
            # governance data (validate_dependency_policy refuses the same
            # state at export).
            raise StandardsError(
                f"dependency_policy_invalid: no policy row for standard {entry.id!r}"
            )
        yanked = {record.version: record for record in row.yanked}
        served = served_versions(policy, view, entry.id)
        move_to = max(served, key=version_tuple) if served else row.lower
        for version in sorted(retained, key=version_tuple):
            stage = promoted.get((entry.id, version))
            stage_cell = f"released (promoted from {stage})" if stage else "released"
            range_cell = "in range" if row.in_range(version) else "out of range"
            record = yanked.get(version)
            if record is None:
                yank_cell = "—"
            else:
                yank_cell = (
                    f"yanked (since {record.since}) — {record.reason}; move-to {move_to}"
                )
            note_cell = row.versions.get(version, "—")
            lines.append(
                f"| {_cell(entry.id)} | {_cell(version)} | {_cell(stage_cell)} "
                f"| {_cell(range_cell)} | {_cell(yank_cell)} | {_cell(note_cell)} |"
            )
    lines.append("")
    return "\n".join(lines)


def check_matrix(root: Path) -> list[str]:
    """``[]`` when the committed matrix equals a fresh render; else one failure."""
    committed = root / DOCS_PATH
    if not committed.is_file():
        return [f"stale_matrix: {DOCS_PATH} absent; run python -m benchweave.standards matrix"]
    if committed.read_text(encoding="utf-8") != render_matrix(root):
        return [
            f"stale_matrix: {DOCS_PATH} differs from the rendered matrix; "
            "run python -m benchweave.standards matrix"
        ]
    return []


def _guidance(entry: StandardEntry, notes: str | None) -> str:
    if entry.status == "deprecated":
        if notes:
            return f"Deprecated — {notes}"
        return "Deprecated — migration guidance pending (compatibility.notes unfilled)"
    if entry.supersedes:
        return f"Supersedes {entry.supersedes}"
    return "—"


def _sources(main_url: str, sdk_url: str) -> str:
    # Both URL helpers fail closed, so the unlinked-cell degradation is
    # unreachable: an honest cell or a refusal, never a silent substitution.
    return f"[main repo]({main_url}) · [sdk repo]({sdk_url})"


def _main_repo_url(root: Path) -> str:
    """Main-repo URL from pyproject ``[project.urls]`` — committed data."""
    with (root / "pyproject.toml").open("rb") as handle:
        urls = tomllib.load(handle).get("project", {}).get("urls", {})
    url = urls.get("Repository") if isinstance(urls, dict) else None
    if not isinstance(url, str) or not url:
        raise StandardsError(
            "main_repo_url_absent: pyproject.toml [project.urls] Repository; "
            "the matrix renders committed files only"
        )
    return url


def _sdk_repo_url(root: Path) -> str:
    """SDK-repo URL from the committed ``.gitmodules`` submodule declaration."""
    result = subprocess.run(  # noqa: S603 — fixed argv
        [  # noqa: S607 — PATH git is the supported invocation
            "git",
            "config",
            "--file",
            str(root / ".gitmodules"),
            "--get",
            "submodule.packages/sdk.url",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    url = result.stdout.strip() if result.returncode == 0 else ""
    if not url:
        raise StandardsError(
            "sdk_repo_url_absent: .gitmodules submodule.packages/sdk.url; "
            "the matrix renders committed files only"
        )
    return url.removesuffix(".git")


def _cell(value: str) -> str:
    # Operator-authored text (compatibility notes, yank reasons, note
    # pointers) must never break the row: neutralise pipes AND newlines,
    # the two characters a markdown table cannot carry.
    return value.replace("|", "\\|").replace("\n", " ")
