export type ObservationValue = boolean | number | string | null;
export type PreviewSeverity = "neutral" | "info" | "success" | "warning" | "critical" | "trip";
export interface PreviewObservation { binding_id: string; value: ObservationValue; unit: string | null; quality: string; freshness_ms: number | null; provenance: string }
export interface SimulatedReceipt { binding_id: string; outcome: string; message: string }
export interface PreviewScenario { id: string; title: string; description: string; timestamp_strategy: "fixed" | "relative"; observations: readonly PreviewObservation[]; permissions: readonly string[]; lease_state: string; approval_state: string; unavailable_panels: readonly string[]; expected_severity: PreviewSeverity; request_outcomes: readonly SimulatedReceipt[]; baseline: boolean }
export interface PreviewDocument { api_version: 1; renderer_version: string; simulation: true; plugin_id: string; pages: readonly Record<string, unknown>[]; scenarios: readonly PreviewScenario[] }
type Fetcher = typeof fetch;
const object = (value: unknown, code: string): Record<string, unknown> => { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(code); return value as Record<string, unknown> };
const text = (value: unknown, code: string): string => { if (typeof value !== "string") throw new Error(code); return value };
const texts = (value: unknown, code: string): string[] => { if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) throw new Error(code); return value };
const finite = (value: unknown, code: string): number => { if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(code); return value };
function decodeObservation(value: unknown): PreviewObservation { const row = object(value, "preview_invalid_observation"); const observed = row.value; if (!(observed === null || typeof observed === "string" || typeof observed === "boolean" || typeof observed === "number")) throw new Error("preview_invalid_value"); if (typeof observed === "number" && !Number.isFinite(observed)) throw new Error("preview_non_finite"); return { binding_id: text(row.binding_id, "preview_invalid_binding"), value: observed, unit: row.unit === null ? null : text(row.unit, "preview_invalid_unit"), quality: text(row.quality, "preview_invalid_quality"), freshness_ms: row.freshness_ms === null ? null : finite(row.freshness_ms, "preview_invalid_freshness"), provenance: text(row.provenance, "preview_invalid_provenance") }; }
function decodeReceipt(value: unknown): SimulatedReceipt { const row = object(value, "preview_invalid_receipt"); return { binding_id: text(row.binding_id, "preview_invalid_receipt_binding"), outcome: text(row.outcome, "preview_invalid_receipt_outcome"), message: text(row.message, "preview_invalid_receipt_message") }; }
function decodeScenario(value: unknown): PreviewScenario { const row = object(value, "preview_invalid_scenario"); if (!Array.isArray(row.observations) || !Array.isArray(row.request_outcomes)) throw new Error("preview_invalid_scenario_arrays"); const severity = text(row.expected_severity, "preview_invalid_severity") as PreviewSeverity; if (!["neutral", "info", "success", "warning", "critical", "trip"].includes(severity)) throw new Error("preview_invalid_severity"); const timestamp = text(row.timestamp_strategy, "preview_invalid_timestamp"); if (timestamp !== "fixed" && timestamp !== "relative") throw new Error("preview_invalid_timestamp"); if (typeof row.baseline !== "boolean") throw new Error("preview_invalid_baseline"); return { id: text(row.id, "preview_invalid_scenario_id"), title: text(row.title, "preview_invalid_scenario_title"), description: text(row.description, "preview_invalid_scenario_description"), timestamp_strategy: timestamp, observations: row.observations.map(decodeObservation), permissions: texts(row.permissions, "preview_invalid_permissions"), lease_state: text(row.lease_state, "preview_invalid_lease"), approval_state: text(row.approval_state, "preview_invalid_approval"), unavailable_panels: texts(row.unavailable_panels, "preview_invalid_panels"), expected_severity: severity, request_outcomes: row.request_outcomes.map(decodeReceipt), baseline: row.baseline }; }
export function decodePreview(value: unknown): PreviewDocument { const row = object(value, "preview_invalid_document"); if (row.api_version !== 1) throw new Error(`preview_api_version: expected 1, received ${String(row.api_version)}`); if (row.simulation !== true || !Array.isArray(row.scenarios) || !Array.isArray(row.pages)) throw new Error("preview_invalid_document"); const scenarios = row.scenarios.map(decodeScenario); const pages = row.pages.map((page) => object(page, "preview_invalid_page")); const ids = new Set<string>(); for (const scenario of scenarios) { if (ids.has(scenario.id)) throw new Error(`preview_duplicate_scenario: ${scenario.id}`); ids.add(scenario.id); } return { api_version: 1, renderer_version: text(row.renderer_version, "preview_invalid_renderer"), simulation: true, plugin_id: text(row.plugin_id, "preview_invalid_plugin_id"), pages, scenarios }; }
async function json(response: Response): Promise<unknown> { if (!response.ok) throw new Error(`preview_http_error: ${response.status}`); return response.json(); }
export async function fetchPreview(baseUrl = "", fetcher: Fetcher = fetch): Promise<PreviewDocument> { return decodePreview(await json(await fetcher(`${baseUrl}/api/v1/preview`, { cache: "no-store" }))); }
export async function requestSimulatedAction(baseUrl: string, scenarioId: string, bindingId: string, value: ObservationValue, fetcher: Fetcher = fetch): Promise<SimulatedReceipt> { const response = await fetcher(`${baseUrl}/api/v1/scenarios/${encodeURIComponent(scenarioId)}/requests`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ binding_id: bindingId, value }) }); return decodeReceipt(await json(response)); }
