"""The plugin-developer skill's question set is derived from the corpus.

Every expected term is read from the vendored schemas at TEST time (issue
#71 slice-2 design record section 8) — nothing is hard-coded. Deleting a
real question from the skill goes RED; renaming a schema field goes RED
here first, because the pin follows the standard, not prose memory. This
is substring presence over generated bytes, deliberately NOT prose parsing
(the skills format stays unstandardised — D2 deferred).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

SDK_SRC = Path(__file__).resolve().parents[2] / "packages/sdk/src"
if str(SDK_SRC) not in sys.path:
    sys.path.insert(0, str(SDK_SRC))

from benchweave_sdk.scaffold import create_project  # noqa: E402

PACKAGE = "lumen_probe"
STANDARDS = SDK_SRC / "benchweave_sdk" / "standards"


def _descriptor_schema() -> dict[str, Any]:
    document: dict[str, Any] = json.loads(
        (STANDARDS / "otdp/0.2.2/otdp-device-descriptor.schema.json").read_text()
    )
    return document


def _registry_schema() -> dict[str, Any]:
    document: dict[str, Any] = json.loads(
        (STANDARDS / "registry/0.1.1/release-manifest.schema.json").read_text()
    )
    return document


def _require(mapping: Any, keys: tuple[str, ...]) -> tuple[str, ...]:
    """KeyError-loud presence check over schema properties.

    The capture/stream/diagnostics keys are the elicitation's declared
    concern; each is looked up in the schema's top-level properties so a
    renamed property fails the derivation loudly instead of passing
    silently as an unverified literal.
    """
    for key in keys:
        _ = mapping[key]
    return keys


def _expected_terms() -> dict[str, list[str]]:
    """Derive the elicitation vocabulary from the vendored corpus itself."""
    schema = _descriptor_schema()
    props, defs = schema["properties"], schema["$defs"]

    def variants() -> list[tuple[str, dict[str, Any]]]:
        node = props["transport"]
        if "$ref" in node:
            node = defs[node["$ref"].split("/")[-1]]
        return [
            (variant["$ref"].split("/")[-1], defs[variant["$ref"].split("/")[-1]])
            for variant in node["oneOf"]
        ]

    policy = defs["operationPolicy"]["properties"]
    parameter = defs["parameter"]["properties"]
    identity = defs["identity"]["properties"]
    adapter = defs["adapter"]["properties"]
    channels: Any = props["channels"]["items"]["properties"]
    terms: dict[str, list[str]] = {
        "verbs": sorted(props["operations"]["properties"]),
        "operation-policy-fields": sorted(policy),
        "operation-policy-enums": sorted(
            {
                value
                for field in ("side_effect", "retry", "completion")
                for value in policy[field]["enum"]
            }
        ),
        "identity-fields": sorted(identity),
        "identity-enums": sorted(
            {
                value
                for field in ("strategy", "firmware_policy")
                for value in identity[field]["enum"]
            }
        ),
        "adapter-fields": sorted(adapter),
        "parameter-fields": sorted(parameter),
        "parameter-enums": sorted(
            {
                value
                for field in ("type", "access", "semantic", "hazard_class")
                for value in parameter[field]["enum"]
            }
        ),
        "transport-types": [
            variant["properties"]["type"]["const"] for _name, variant in variants()
        ],
        "transport-settings-keys": sorted(
            {
                key
                for _name, variant in variants()
                for key in variant["properties"].get("settings", {}).get("properties", {})
            }
        ),
        "channel-fields": sorted(channels),
        "capture-stream-diagnostics-keys": list(
            _require(
                props,
                (
                    "channels",
                    "capture_formats",
                    "capture_limits",
                    "stream_limits",
                    "diagnostics",
                ),
            )
        ),
        "class-ids": sorted(
            entry["id"]
            for entry in json.loads(
                (STANDARDS / "otdp/0.2.2/device-profile-catalog.json").read_text()
            )["profiles"]
        ),
        "manifest-roles": sorted(
            _registry_schema()["properties"]["payload"]["properties"]["files"]["items"]["properties"][
                "role"
            ]["enum"]
        ),
        "evidence-levels": sorted(
            _registry_schema()["properties"]["evidence"]["items"]["properties"]["level"]["enum"]
        ),
        "manifest-kinds": sorted(_registry_schema()["properties"]["kind"]["enum"]),
    }
    return terms


def _develop_skill_text(tmp_path: Path) -> str:
    project = tmp_path / "proj"
    create_project(project, PACKAGE)
    return (project / f"src/{PACKAGE}/skills/develop-plugin/SKILL.md").read_text(encoding="utf-8")


def test_elicitation_covers_real_authoring_surfaces(tmp_path: Path) -> None:
    terms = _expected_terms()
    # The instrument refuses an empty or shrunken derivation outright: an
    # empty expected set would pass any prose and prove nothing (the
    # design's UNDERPOWERED clause).
    floors = {
        "verbs": 10,
        "operation-policy-fields": 5,
        "operation-policy-enums": 8,
        "identity-fields": 5,
        "identity-enums": 5,
        "adapter-fields": 5,
        "parameter-fields": 12,
        "parameter-enums": 16,
        "transport-types": 9,
        "transport-settings-keys": 20,
        "channel-fields": 5,
        "capture-stream-diagnostics-keys": 5,
        "class-ids": 12,
        "manifest-roles": 11,
        "evidence-levels": 3,
        "manifest-kinds": 3,
    }
    for category, floor in floors.items():
        assert len(terms[category]) >= floor, f"derived {category} shrank: {terms[category]}"
    text = _develop_skill_text(tmp_path)
    missing = {
        category: [term for term in expected if not re.search(rf"\b{re.escape(term)}\b", text)]
        for category, expected in terms.items()
    }
    missing = {category: absent for category, absent in missing.items() if absent}
    assert not missing, f"develop-plugin skill is missing derived terms: {missing}"


def test_skill_states_safety_boundary(tmp_path: Path) -> None:
    """Both seeded skills carry the no-hardware/no-publication rails (an
    output pin on our own bytes; R11's mitigation lives in the text itself)."""
    project = tmp_path / "proj"
    create_project(project, PACKAGE)
    rails = ("do not contact hardware", "without separate authority")
    for relative in (
        f"src/{PACKAGE}/skills/develop-plugin/SKILL.md",
        f"src/{PACKAGE}/skills/drive-device/SKILL.md",
    ):
        text = (project / relative).read_text(encoding="utf-8")
        for rail in rails:
            assert rail in text, f"{relative} drops the safety rail: {rail!r}"
