"""The plugin catalogue panel contract (issue #224 slice 2, CR-20/21/22/23).

The panel's rows are a committed generated block in ``website/index.html``
between machine markers, rewritten only by
``scripts/website/render_plugins_panel.py`` (invariants CON-13 amendment).
This suite pins generation discipline (B2's plants), the default-view rule
(B3 honesty), the yanked-row consequence (B1's gateway half), the honesty
sentence (CR-23), and the renderer's fail-closed arms. The class-11 literal
exemption boundary lives in ``test_website_stamps.py``; the search truth is
``test_website_plugins_search.py``; the wiring proof is the docs workflow's
browser arm.

Plants operate on sandbox copies; the committed trees are never written.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
FIXTURE = FIXTURES / "plugins-index.fixture.json"
INDEX = ROOT / "website" / "index.html"
MIRROR = ROOT / "website" / "plugins-index.json"
REF = ROOT / "website" / "plugins-index.ref"
RENDER_TOOL = ROOT / "scripts" / "website" / "render_plugins_panel.py"

SEMVER_RE = re.compile(r"\d+\.\d+\.\d+")

# The honesty sentence (CR-23) — string-pinned so a drift back to a
# service claim reddens. Neither sentence contains the phrase
# "registry service" while no such service exists.
HONESTY_SENTENCE = (
    "a catalogue of published, signed releases now exists as a git-native "
    "registry repository of record"
)
HONESTY_NO_SERVICE = "no hosted registry front end and no device-install command exist"

# CR-20's seven contract fields, as the card slots the renderer must carry
# (rendered or explicitly "none" — the value arms are below).
CONTRACT_SLOTS = (
    "display-name",
    "summary",
    "publisher",
    "licence",
    "maintenance",
    "kind",
    "release-id",
    "version",
    "digest",
    "compat",
    "evidence-link",
    "source-revision",
)


def _module() -> Any:
    import importlib.util

    spec = importlib.util.spec_from_file_location("render_plugins_panel", RENDER_TOOL)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _html() -> str:
    return INDEX.read_text(encoding="utf-8")


def _block() -> str | None:
    result: str | None = _module().extract_block(_html())
    return result


def _run_tool(*args: str, root: Path | None = None) -> subprocess.CompletedProcess[str]:
    cmd = [sys.executable, str(RENDER_TOOL)]
    if root is not None:
        cmd += ["--root", str(root)]
    cmd += list(args)
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def _sandbox(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    (root / "website").mkdir(parents=True)
    shutil.copytree(ROOT / "website", root / "website", dirs_exist_ok=True)
    (root / "scripts" / "website").mkdir(parents=True)
    shutil.copy2(RENDER_TOOL, root / "scripts" / "website" / RENDER_TOOL.name)
    return root


def test_committed_block_matches_the_mirror() -> None:
    """The render guard: the committed block byte-equals a fresh render of the
    committed mirror. Catches a hand-edited panel row and a hand-edited
    mirror row that changes rendered content (a non-rendering field rides
    the authority pin instead — that is not this arm's catch)."""
    block = _block()
    assert block is not None, "panel marker pair missing from website/index.html"
    fresh = _module().render_panel_rows(MIRROR.read_bytes())
    assert block == fresh, (
        "panel_drift: the committed panel block differs from a fresh render of the "
        "committed mirror (hand-edited panel row or hand-edited mirror row)"
    )


def test_block_shape_pins() -> None:
    """The block carries the marker pair exactly once, no `{{`, and no
    three-component version literal (the class-11 ban at the block level)."""
    html = _html()
    begin = "bw:plugins-panel begin"
    end = "bw:plugins-panel end"
    assert html.count(begin) == 1, "panel begin marker not unique"
    assert html.count(end) == 1, "panel end marker not unique"
    block = _block()
    assert block is not None
    assert "{{" not in block, "stamp-token delimiter inside the generated block"
    literals = SEMVER_RE.findall(block)
    assert not literals, f"version literal(s) inside the generated block: {literals}"


def test_template_card_is_the_single_shape_source() -> None:
    """The hidden template card (cloned by the page's JS for on-demand rows)
    is generated by the same renderer — one shape source for committed and
    cloned cards."""
    block = _block()
    assert block is not None
    assert block.count("data-bw-template") == 1, "exactly one template card required"
    assert block.startswith("<template data-bw-template>"), block[:60]


def test_default_block_excludes_non_default_kinds_and_unsigned() -> None:
    """B3's honesty arm on the fixture: the static block is exactly the
    admitted-release + signed-valid rows. A community-shared row, an
    in-tree-fixture row, and an admitted-but-UNSIGNED row are all absent
    from the static bytes (reachable only through explicit filters)."""
    block = _module().render_panel_rows(FIXTURE.read_bytes())
    for pid in (
        "copperleaf-labs/copperleaf-daq",
        "copperleaf-labs/copperleaf-shunt",
        "copperleaf-labs/copperleaf-therm",
        "northwind-instruments/northwind-load",
        "northwind-instruments/northwind-psu",
        "northwind-instruments/northwind-scope",
    ):
        assert f'data-bw-package-id="{pid}"' in block, f"default row missing: {pid}"
    for pid in (
        "harborline-systems/harborline-relay",  # admitted-release but unsigned
        "harborline-systems/harborline-relay16",  # community-shared
        "harborline-systems/harborline-pwm",  # community-shared + unsigned
        "northwind-instruments/northwind-fixture",  # in-tree-fixture
    ):
        assert f'data-bw-package-id="{pid}"' not in block, f"non-default row rendered: {pid}"


def test_yanked_release_is_absent_from_the_block() -> None:
    """B1's yank arm, gateway half (the mirrored consequence): the registry
    generator drops a yanked release's row from the index (registry test
    proves that half), so the mirror carries no such row — and neither the
    block nor the catalogue can resurrect it. Here: a mirror without the
    yanked package's row renders a block with no card for it."""
    document = json.loads(MIRROR.read_text(encoding="utf-8"))
    rows = document["rows"]
    assert rows, "the dogfooded release must seed the mirror"
    dropped = rows[0]
    pid = str(dropped["package_id"])
    block = _module().render_panel_rows(MIRROR.read_bytes())
    assert f'data-bw-package-id="{pid}"' in block, "precondition: the row renders today"
    document["rows"] = [row for row in rows if row.get("package_id") != pid]
    block_without = _module().render_panel_rows(json.dumps(document).encode())
    assert f'data-bw-package-id="{pid}"' not in block_without, (
        "a row absent from the mirror must be absent from the block"
    )


def test_empty_mirror_renders_the_honest_empty_sentence() -> None:
    """Zero default rows never yields an empty panel — the honest empty
    sentence stands instead."""
    block = _module().render_panel_rows(b'{"index_version": 1, "rows": []}')
    assert "No published releases yet" in block
    assert "data-bw-template" in block, "the template card survives the empty state"


def test_static_cards_carry_the_seven_contract_fields() -> None:
    """CR-20's structural arm: every card carries the contract slots (rendered
    or explicitly "none"). Value-level none-arms are test_default… and the
    evidence/advisories arms below."""
    block = _module().render_panel_rows(FIXTURE.read_bytes())
    cards = block.split('data-bw-package-id="')[1:]  # one chunk per real card
    assert len(cards) == 6, f"the fixture's default view is 6 cards, got {len(cards)}"
    for card in cards:
        for slot in CONTRACT_SLOTS:
            assert f'data-bw-slot="{slot}"' in card, f"card lacks contract slot {slot}"


def test_explicit_none_for_absent_evidence_and_advisories() -> None:
    """CR-20's "or explicitly none": a row with empty evidence renders "no
    test evidence"; a row with no advisories renders "no advisories"."""
    block = _module().render_panel_rows(FIXTURE.read_bytes())
    assert "no test evidence" in block  # the fixture rows with empty evidence[]
    assert "no advisories" in block


def test_honesty_sentence_is_string_pinned() -> None:
    """CR-23: the updated honesty sentence is pinned verbatim, and states the
    catalogue's actual posture — a git-native repository of record, no
    hosted front end, installation stays local admission."""
    html = _html()
    assert HONESTY_SENTENCE in html, "the honesty sentence drifted"
    assert HONESTY_NO_SERVICE in html, "the honesty sentence's no-service clause drifted"


def test_no_registry_service_language_on_the_panel() -> None:
    """B3's string arm: the words "registry service" appear nowhere in the
    plugins panel section or in the pinned honesty sentence — the phrase is
    the stale framing (it implies a service-shaped thing that does not
    exist)."""
    html = _html()
    start = html.index('<section class="panel" id="panel-plugins">')
    panel = html[start : html.index("</section>", start)]
    assert "registry service" not in panel.lower(), "panel claims a registry service"
    for sentence in (HONESTY_SENTENCE, HONESTY_NO_SERVICE):
        assert "registry service" not in sentence.lower()


def test_marker_display_map_twins_agree() -> None:
    """The unverified-marker display map has two carriers (Python at
    generation, JS for cloned rows); the twins must stay equal in their
    mapping or a marker would render two ways on one page."""
    js = (ROOT / "website" / "assets" / "plugins.js").read_text(encoding="utf-8")
    pattern = re.compile(r"'([a-z0-9-]+)':\s*'([^']*)'")
    js_map = dict(pattern.findall(js.split("MARKER_DISPLAY", 1)[1].split("}", 1)[0]))
    assert js_map == _module().MARKER_DISPLAY, (js_map, _module().MARKER_DISPLAY)


def test_renderer_refuses_unknown_kind() -> None:
    """Fail-closed: an unknown kind in the mirror refuses at generation."""
    bad = json.dumps(
        {"index_version": 1, "rows": [{"kind": "mystery", "package_id": "a/b"}]}
    ).encode()
    with pytest.raises(SystemExit, match="panel_input_invalid:"):
        _module().render_panel_rows(bad)


def test_renderer_refuses_an_unparseable_mirror() -> None:
    with pytest.raises(SystemExit, match="panel_input_invalid:"):
        _module().render_panel_rows(b"not json at all")


def test_renderer_refuses_a_literal_in_its_output() -> None:
    """The class-11 ban holds at generation time: a mirror value carrying a
    three-component version literal refuses rather than rendering."""
    row = {
        "kind": "admitted-release",
        "signature_state": "signed-valid",
        "package_id": "a/b",
        "summary": "ready at version 1.2.3",
    }
    with pytest.raises(SystemExit, match="panel_literal_refused:"):
        _module().render_panel_rows(json.dumps({"rows": [row]}).encode())


def test_renderer_refuses_braces_in_its_output() -> None:
    row = {
        "kind": "admitted-release",
        "signature_state": "signed-valid",
        "package_id": "a/b",
        "summary": "see {{stg-otdp}}",
    }
    with pytest.raises(SystemExit, match="panel_braces_refused:"):
        _module().render_panel_rows(json.dumps({"rows": [row]}).encode())


def test_hand_edited_panel_row_refuses(tmp_path: Path) -> None:
    """B2 plant 3: a hand-edited panel row is refused by the tool's --check
    with its machine prefix — the guard, not a sweep."""
    root = _sandbox(tmp_path)
    index = root / "website" / "index.html"
    html = index.read_text(encoding="utf-8")
    planted = html.replace("data-bw-slot=\"summary\">", "data-bw-slot=\"summary\">hand-edited ", 1)
    assert planted != html
    index.write_text(planted, encoding="utf-8")
    result = _run_tool("--check", root=root)
    assert result.returncode == 1, result.stdout + result.stderr
    assert "panel_drift:" in result.stderr


def test_hand_edited_mirror_row_refuses(tmp_path: Path) -> None:
    """B2 plant 2, render half: a hand-edited mirror row that changes rendered
    content reddens --check (the committed block no longer matches a fresh
    render of the planted mirror). The authority pin catches non-rendering
    edits — that is the other half, scripts/website/check_mirror_authority.py."""
    root = _sandbox(tmp_path)
    mirror = root / "website" / "plugins-index.json"
    document = json.loads(mirror.read_text(encoding="utf-8"))
    document["rows"][0]["summary"] = "hand-edited summary"
    mirror.write_text(json.dumps(document, sort_keys=True, separators=(",", ":")), encoding="utf-8")
    result = _run_tool("--check", root=root)
    assert result.returncode == 1, result.stdout + result.stderr
    assert "panel_drift:" in result.stderr


def test_write_then_check_round_trips(tmp_path: Path) -> None:
    """The sync path's write is idempotent: after --write, --check is green,
    and a second --write leaves the file byte-identical."""
    root = _sandbox(tmp_path)
    index = root / "website" / "index.html"
    first = _run_tool("--write", root=root)
    assert first.returncode == 0, first.stderr
    after_write = index.read_bytes()
    check = _run_tool("--check", root=root)
    assert check.returncode == 0, check.stderr
    second = _run_tool("--write", root=root)
    assert second.returncode == 0, second.stderr
    assert index.read_bytes() == after_write, "a second --write moved the bytes"
