"""Shared machinery for the machine-written validation-report family.

One renderer, one author-side writer epilogue, one manifest-derived version
lookup; the family scripts supply only their constants and their checks
(issue #102 D1, generalizing the #79 devices writer and its #102 D2
manifest derivation to every suite with a machine-written report).
"""

import json
import sys
from pathlib import Path
from typing import NoReturn


def active_standard_version(standards_root: Path, standard_id: str) -> str:
    """The active version of a standard, derived from the standards manifest.

    Never a hardcoded literal and never a silent fallback: a missing manifest
    or a manifest without the standard's entry is a loud refusal — the corpus
    a family script validates IS the manifest's active version. Only the
    refusal PREFIX is byte-stable across the family: ``{standard_id}_manifest_absent:``
    is byte-identical to the historical ``otdp_manifest_absent:`` for devices
    (what the #119/#125 surfaces match on); the message text after the prefix
    is generic and lowercase ("active otdp", not the historical "active OTDP").
    """

    manifest_path = standards_root / "standards-manifest.json"
    if not manifest_path.is_file():
        raise SystemExit(
            f"{standard_id}_manifest_absent: standards-manifest.json not found — the "
            f"active {standard_id} version cannot be derived"
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    for entry in manifest.get("standards", []):
        if entry.get("id") == standard_id:
            version = entry.get("version")
            if isinstance(version, str) and version:
                return version
    raise SystemExit(
        f"{standard_id}_manifest_absent: standards-manifest.json carries no {standard_id} "
        f"entry with a version — the active {standard_id} version cannot be derived"
    )


def _marker(script: str) -> str:
    return (
        f"<!-- Generated by {script} --write-report — regenerate on check changes; "
        "do not hand-edit. -->"
    )


def render(
    checks: list[tuple[str, bool]],
    *,
    marker: str,
    title: str,
    coverage: str,
    limit: str | None = None,
) -> str:
    """Render a validation report markdown from a check list.

    Pure and order-canonical: the ``## Checks`` list is emitted sorted by
    name because suite accumulation order is partly glob order
    (directory-entry order), which is not portable across platforms; the
    rendered bytes are a function of the check set only. ``limit`` is
    optional for suites whose prose keeps coverage and limits in one
    paragraph.
    """

    passed = sum(1 for _, ok in checks if ok)
    lines: list[str] = [
        marker,
        "",
        title,
        "",
        f"**Result: {passed}/{len(checks)} checks passed; {len(checks) - passed} failed.**",
        "",
        coverage,
    ]
    if limit is not None:
        lines += ["", limit]
    lines += ["", "## Checks", ""]
    lines.extend(f"- {'PASS' if ok else 'FAIL'}: {name}" for name, ok in sorted(checks))
    lines.append("")
    return "\n".join(lines)


def main(
    checks: list[tuple[str, bool]],
    out_path: Path,
    *,
    script: str,
    title: str,
    coverage: str,
    limit: str | None = None,
) -> NoReturn:
    """The shared author-side epilogue: report, then maybe write the report.

    Only reachable under a real ``__main__`` — each family script calls this
    from its own ``if __name__ == "__main__":`` block, and ``runpy.run_path``
    executes the module body with ``__name__ == "<run_path>"``, so the
    pytest harness can never reach the writer. Refuses (exit 1) to write
    when any check fails. Always raises ``SystemExit`` (the refuse path with
    code 1, the tail with the run's overall verdict) — hence ``NoReturn``.
    """

    failures = [name for name, ok in checks if not ok]
    for failure in failures:
        print("FAIL:", failure)
    print(f"{len(checks) - len(failures)}/{len(checks)} checks passed")
    if "--write-report" in sys.argv[1:]:
        if failures:
            print(f"refusing to write the validation report: {len(failures)} failing check(s)")
            raise SystemExit(1)
        out_path.write_text(
            render(
                [(str(name), bool(ok)) for name, ok in checks],
                marker=_marker(script),
                title=title,
                coverage=coverage,
                limit=limit,
            ),
            encoding="utf-8",
            newline="\n",
        )
        print(f"wrote {out_path}")
    raise SystemExit(bool(failures))
